jobs:
  backend-test:
    executor:
      name: node/default
    steps:
      - checkout
      - cd backend/ && npm install
      - cd backend/ && npm test
           

version: 2.1
orbs:
  node: circleci/node@1.1.6
workflows:
    test:
      jobs:
        - backend-test