version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  backend-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node:
          steps:
            - run: cd backend/ && npm install
            - run: cd backend/ && npm test
workflows:
    test:
      jobs:
        - backend-test