version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  backend-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: npm-install
          command: cd backend && npm install
      - run:
          name: test
          command: cd backend && npm test
      - store_artifacts:
          path: backend/coverage
          prefix: coverage
workflows:
    test:
      jobs:
        - backend-test